name: Test and Lint

on:
  workflow_call:
    secrets:
      DOCKERHUB_USER:
        required: true
        description: "Dockerhub username"
      DOCKERHUB_TOKEN:
        required: true
        description: "token for dockerhub"

jobs:
  python:
    name: Python
    runs-on: ubuntu-22.04
    steps:
      - name: login to Docker hub
        uses: docker/login-action@v3 # This is the action we are using to login to Docker Hub
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4 # This is the action we are using to checkout the code
      - name: Test # this run for unit test
        run: docker compose run --rm app sh -c "python mmanage.py wait_for_db && python manage.py test"
      - name: Python flake8 # this run for linting use tool flake8
        run: docker compose run --rm app sh -c "flake8"
